### ISSUE TITLE
Tracking exactly what is installed on ospc.org and when

### ISSUE THREAD

**Issue by PeterDSteinberg** [OpenSourcePolicyCenter/PolicyBrain#581]
Related to the #560 discussion on the release process we discussed, among other things, tagging the webapp-public master commits we are releasing.  This will help better track what is installed.  We also can do the following activities to better track the exactly what we install on ospc.org and its backend workers over time.  TODO:

 * [ ] Make a google doc for internal usage where we can write down exactly what we deployed to ospc.org and on which date and time we did it
 * [ ] Keep a folder on google drive where we upload yaml files that are created by `conda env export` on a backend or frontend worker after a deployment
       * [ ] It would be good to have this as a reusable script, but even if the script is not done in time for the next deploy, we can go ahead and do `conda env export` manually.

**Comment by martinholmer** [comment]
@PeterDSteinberg said:
> Related to the #560 discussion on the release process we discussed, among other things, tagging the webapp-public master commits we are releasing. This will help better track what is installed.

Yes, I agree completely.  It seems to me we want a record of the releases being used by TaxBrain for the following repos: webapp-public, Tax-Calculator (taxcalc package), OG-USA (ogusa package), and B-Tax (btax package).

This information should appear in **two** places that can be viewed by the public.

First, the current release numbers should be a the bottom of the TaxBrain page that appears when you click on `What is TaxBrain?`.  Right now there is this cryptic information:
```
          CODE BUILD

Version 0.9.0.d79abf - GitHub
```

And second, a history of this release information should be added to a new webapp-public `RELEASES.md` file, similar to the one now being used in the Tax-Calculator repo.

I think your suggestion of storing this historical information in a google doc is a very bad idea.  This is an open source project.  This basic information should be public.

@MattHJensen @PeterDSteinberg @brittainhard @jbcrail @hdoupe

**Comment by hdoupe** [comment]
I agree with @martinholmer that these documents should be public.  I don't think that 

```
          CODE BUILD

Version 0.9.0.d79abf - GitHub
```

is too cryptic except for the "d79abf" part.  I think "Version 0.9.0" is fine.  However, while checking this out, I noticed that the link you select when you click `Version 0.9.0.d79abf - GitHub` is 

`https://github.com/OpenSourcePolicyCenter/Tax-Calculator`

when I think it should be this `https://github.com/open-source-economics/Tax-Calculator/tree/0.9.0` as found [on the releases page](https://github.com/open-source-economics/Tax-Calculator/releases).

**Comment by martinholmer** [comment]
@hdoupe said in #581 he thought only the commit number `.d79abf` was cryptic.

I agree.  The commit number adds no extra information, it just adds potential confusion for TaxBrain users who are not knowledgeable about git and version control.

Good catch on the need to have the link be something like:
```
https://github.com/open-source-economics/Tax-Calculator/tree/0.9.0
```
@MattHJensen @PeterDSteinberg @brittainhard @jbcrail

**Comment by hdoupe** [comment]
I would also like to know what is stalled on ospc.org and when it was installed. However, I think it would be better to keep track of this in a container registry or something like that. This would be better addressed in a comprehensive issue on deployment strategy.

**Comment by hdoupe** [comment]
Closed #581
