### ISSUE TITLE
PolicyBrain 1.2.0

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#734]
Issues for the next release:

- [x] #668, #733 Upgrade to Tax-Calculator 0.13.0 
  - #668 -- Includes everything except for UBI inputs
- [ ] #687 Dynamic CDNs for bokeh
  - #688 -- This works.  It just needs to be merged
- [x] #699 Testing push issue
  - #706 -- This will be resolved by the end of today, 11/8.

The goal for this release is to get Tax-Calculator 0.13.0 up on TaxBrain as soon as possible.  The estimated time for a production release is 11/17 - 11/22.

**Comment by hdoupe** [comment]
@GoFroggyRun and I decided to push the CPS button to the next release.  That means that this version will have the new Tax-Calculator parameters, and the option for using the PUF instead of the CPS will be hard-coded to only using the PUF.

PR #738 will be ready for review by the end of today.  Hopefully, we can merge this on Monday, push to the test server on Monday, and push to production on Tuesday night.

How does that sound?

cc @MattHJensen @GoFroggyRun @andersonfrailey

**Comment by martinholmer** [comment]
@hdoupe said:
>  Hopefully, we can merge this on Monday, push to the test server on Monday, and push to production on Tuesday night.

Will this new 1.2.0 version of PolicyBrain be using Tax-Calculator release 0.13.1 ?

**Comment by hdoupe** [comment]
@martinholmer yes it will.  I've been working off of TC 0.13.0.  I'll update PR #738 to 0.13.1 shortly.

**Comment by MattHJensen** [comment]
> @martinholmer yes it will. I've been working off of TC 0.13.0. I'll update PR #738 to 0.13.1 shortly.

@hdoupe, do you think you would still be able to get the PB release out by Thanksgiving if we do a new TC 0.13.2 release by end of today and then you include that in the release? 

@martinholmer, would you have an opportunity to do a TC conda release today (I still haven't gotten it working). 

If we include https://github.com/open-source-economics/Tax-Calculator/issues/1671 and https://github.com/open-source-economics/Tax-Calculator/pull/1667 on PolicyBrain then I believe PolicyBrain GUI will be able to analyze the House proposal and the Senate modified chairman's mark. I can work on 1667 today.

**Comment by hdoupe** [comment]
@MattHJensen I think using TC 0.13.2 in this release is feasible if you can get it out by the end of the day.
