### ISSUE TITLE
January/February Release Plan

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#805]
The following 2-3 releases will involve fixes for a few larger issues and many smaller fixes along the way.

Larger issues that need to be resolved (in rough order of priority):
- [x] #794 -- Decile distribution Table entries not correct
  - #804 -- Upgrade to Tax-Calculator 0.15.0
- [x] #811 -- Save model parameters as JSON objects [EDIT: inserted on 2/2/17]
- [x] #765 --  Handle future year reforms for checkboxes
  - #786 -- GUI input types (for further discussion)
- [x] #795 -- _EITC_MinEligAge is not an integer in TaxBrain GUI input
- [ ] #763 -- Issues with `cpi_offset` parameter
- [ ] #539 -- Steps for putting OG-USA back on TaxBrain
  - #710 -- Reinstate OG-USA (needs to be tested and merged)
- [x] #668 -- Update TaxBrain and Tax-Calculator to handle UBI and CPS specific inputs
  - #740 -- Add CPS button
- [ ] #677 -- Out-of-date TaxBrain code in test_celery_tasks.py

Other issues that need to be resolved have a "Priority" tag and are not in the list above. There may be some follow up comments in this issue or in release-specific issues prioritizing the smaller issues.

Feedback and questions on priority in these issues, adding issues, or removing issues are welcome.

NOTE: The first three items are bugs and have high priority. Further, the way I see it, the order of issues #765 and #795 will make the development process go smoother.

**Comment by hdoupe** [comment]
Closing #805. I will open a new issue to outline the remaining items in this issue as well as new bug-fixes and enhancements.
