### ISSUE TITLE
PolicyBrain forthcoming release plan

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/PolicyBrain#927]
Given the complexity of these changes, the merge and deployment will occur in stages. Below is a tentative outline of what each stage should be:

- [ ] PR #921 should be merged once tests pass and with no assumptions of backwards compatibility
- [ ] A pre-release should be issued and deployed to the test app for review and to gather feedback. It should use the Tax-Calculator branch in open-source-economics/Tax-Calculator#2037. It should also use the AWS infrastructure from OpenSourcePolicyCenter/pb_deploy#1 (which should then be merged and a pre-release should be issued)
- [ ] Incorporate feedback and do another pre-release, repeat (2)
- [ ] open-source-economics/Tax-Calculator#2037 needs to be reviewed more thoroughly and tests should be added
- [ ] backwards compatibility issues need to be addressed:
    - [ ] how do we deal with prior behavioral and static simulations
    - [ ] how do we display the outputs from prior runs (a serious effort should be made to display the outputs from all prior runs, including those that are not available right now)
- [ ] tests for new class based view and helper methods on new models

Once these steps are completed, a full release should be issued.

@lucassz @MattHJensen @martinholmer

[Repost of [comment](https://github.com/OpenSourcePolicyCenter/PolicyBrain/pull/921#issuecomment-413266528) in PR #921]
